import React, { useState, useEffect } from 'react';
import { useAuth } from '../../contexts/AuthContext';
import { useNavigate } from 'react-router-dom';
import { db } from '../../services/firebase';
import { collection, query, where, getDocs, addDoc, doc, updateDoc } from 'firebase/firestore';
import { getSickBalance, approveSickRequest } from '../../services/firebase';
import { PDFDownloadLink, Document, Page, Text, View } from '@react-pdf/renderer';
import { CSVLink } from 'react-csv';

export default function Admin() {
  const { user, role } = useAuth();
  const navigate = useNavigate();
  const [employees, setEmployees] = useState([]);
  const [requests, setRequests] = useState([]);
  const [newEmail, setNewEmail] = useState('');
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [auditData, setAuditData] = useState([]);

  useEffect(() => {
    if (user && role === 'employer') {
      loadEmployees();
      loadRequests();
    } else {
      navigate('/login');
    }
  }, [user, role, navigate]);

  const loadEmployees = async () => {
    try {
      const q = query(collection(db, 'users'), where('employerId', '==', user.uid));
      const snapshot = await getDocs(q);
      const employeeList = await Promise.all(snapshot.docs.map(async (d) => ({
        id: d.id,
        email: d.data().email,
        balance: await getSickBalance(d.id)
      })));
      setEmployees(employeeList);
    } catch (err) {
      setError('Error loading employees: ' + err.message);
    }
  };

  const loadRequests = async () => {
    try {
      const q = query(collection(db, 'sickRequests'), where('employerId', '==', user.uid), where('status', '==', 'pending'));
      const snapshot = await getDocs(q);
      const requestList = snapshot.docs.map(d => ({
        id: d.id,
        ...d.data()
      }));
      setRequests(requestList);
    } catch (err) {
      setError('Error loading requests: ' + err.message);
    }
  };

  const addEmployee = async () => {
    try {
      await addDoc(collection(db, 'users'), {
        email: newEmail,
        employerId: user.uid,
        role: 'employee',
        isSmallEmployer: false,  // Default; toggle per employer
        totalHours: 0
      });
      setSuccess('Employee added!');
      setNewEmail('');
      loadEmployees();
    } catch (err) {
      setError('Add employee error: ' + err.message);
    }
  };

  const handleApprove = async (requestId, status) => {
    try {
      await approveSickRequest(requestId, status, user.uid);
      setSuccess('Request updated!');
      loadRequests();
      loadEmployees();
    } catch (err) {
      setError('Approval error: ' + err.message);
    }
  };

  const generateAudit = async () => {
    try {
      const q = query(collection(db, 'workLogs'), where('employerId', '==', user.uid));
      const snapshot = await getDocs(q);
      const auditList = snapshot.docs.map(d => ({
        id: d.id,
        ...d.data()
      }));
      setAuditData(auditList);
      setSuccess('Audit data generated!');
    } catch (err) {
      setError('Audit generation error: ' + err.message);
    }
  };

  const AuditPDF = ({ data }) => (
    <Document>
      <Page size="A4" style={{ padding: 40 }}>
        <View style={{ textAlign: 'center', marginBottom: 20 }}>
          <Text style={{ fontSize: 24, fontWeight: 'bold' }}>ESTA Audit Report</Text>
          <Text style={{ fontSize: 12, marginTop: 5 }}>Michigan Earned Sick Time Act Compliance</Text>
        </View>
        <View style={{ marginBottom: 10 }}>
          <Text>Employer: {user.email}</Text>
          <Text>Date: {new Date().toLocaleDateString()}</Text>
        </View>
        <View style={{ marginBottom: 10 }}>
          <Text>Audit History</Text>
          {data.map((item, i) => (
            <Text key={i}>{item.userId} logged {item.hours} hours on {new Date(item.timestamp.seconds * 1000).toLocaleDateString()}</Text>
          ))}
        </View>
        <Text style={{ fontSize: 10, marginTop: 20 }}>Generated by ESTA Tracker – For internal use only.</Text>
      </Page>
    </Document>
  );

  return (
    <div style={{ padding: '2rem', maxWidth: '600px', margin: 'auto' }}>
      <h1>Employer Admin Dashboard</h1>
      {error && <p style={{ color: 'red' }}>{error}</p>}
      <h2>Add Employee</h2>
      <input placeholder="Employee Email" value={newEmail} onChange={e => setNewEmail(e.target.value)} />
      <button onClick={addEmployee}>Add</button>
      <h2>Employees</h2>
      <ul>
        {employees.map(emp => (
          <li key={emp.id}>
            {emp.email} — Balance: {emp.balance} hours
          </li>
        ))}
      </ul>
      <h2>Pending Requests</h2>
      <ul>
        {requests.map(req => (
          <li key={req.id}>
            {req.userId} requests {req.hours}h ({req.reason})
            <button onClick={() => handleApprove(req.id, 'approved')}>Approve</button>
            <button onClick={() => handleApprove(req.id, 'denied')}>Deny</button>
          </li>
        ))}
      </ul>
      <h2>Audit Exports</h2>
      <button onClick={generateAudit}>Generate Audit Data</button>
      {auditData.length > 0 && (
        <>
          <PDFDownloadLink document={<AuditPDF data={auditData} />} fileName="esta-audit-report.pdf">
            {({ loading }) => <button disabled={loading}>{loading ? 'Generating PDF...' : 'Download PDF Audit'}</button>}
          </PDFDownloadLink>
          <CSVLink data={auditData} filename="esta-audit.csv" className="button">Download CSV Audit</CSVLink>
        </>
      )}
    </div>
  );
}