name: run-firestore-emulator
description: Start Firestore emulator for tests
inputs:
  port:
    description: 'Port to run the Firestore emulator on'
    required: false
    default: '8080'
runs:
  using: 'composite'
  steps:
    - name: Run emulator
      shell: bash
      env:
        EMULATOR_PORT: ${{ inputs.port }}
      run: |
        # Start Google emulators in background; exit if cannot
        gcloud --version || echo "gcloud not installed; rely on firebase-tools"
        npm i -g firebase-tools || true
        nohup firebase emulators:start --only firestore --project test-project --host 127.0.0.1 --port ${EMULATOR_PORT} > firestore-emulator.log 2>&1 &
        # wait for emulator to accept connections
        for i in $(seq 1 20); do
          if nc -z 127.0.0.1 ${EMULATOR_PORT}; then break; fi
          sleep 1
        done
