name: run-firestore-emulator
description: Start Firestore emulator for tests
inputs:
  port:
    description: 'Port to run the Firestore emulator on'
    required: false
    default: '8080'
outputs:
  emulator_pid:
    description: 'PID of the emulator process'
    value: ${{ steps.start-emulator.outputs.pid }}
runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        # Install netcat for port checking
        sudo apt-get update -qq
        sudo apt-get install -y -qq netcat-openbsd || true
        echo "✅ netcat installed"

    - name: Start emulator
      id: start-emulator
      shell: bash
      env:
        EMULATOR_PORT: ${{ inputs.port }}
      run: |
        # Cleanup any existing emulator processes
        pkill -f "firebase.*emulators" || true

        # Check if port is already in use and find alternative
        PORT=${EMULATOR_PORT}
        MAX_PORT_ATTEMPTS=5
        for attempt in $(seq 1 ${MAX_PORT_ATTEMPTS}); do
          if nc -z 127.0.0.1 ${PORT} 2>/dev/null; then
            echo "⚠️ Port ${PORT} is in use, trying next port..."
            PORT=$((PORT + 1))
          else
            break
          fi
        done

        if [ ${PORT} -ne ${EMULATOR_PORT} ]; then
          echo "Using alternative port: ${PORT}"
        fi

        # Install firebase-tools if not available
        if ! command -v firebase &> /dev/null; then
          echo "📦 Installing firebase-tools..."
          npm i -g firebase-tools || true
        fi

        # Start emulator with Java options for stability
        export JAVA_TOOL_OPTIONS="-Xmx512m"
        nohup firebase emulators:start --only firestore --project test-project --host 127.0.0.1 --port ${PORT} > firestore-emulator.log 2>&1 &
        EMULATOR_PID=$!
        echo "pid=${EMULATOR_PID}" >> $GITHUB_OUTPUT
        echo "port=${PORT}" >> $GITHUB_OUTPUT

        # Wait for emulator to accept connections with timeout
        echo "⏳ Waiting for Firestore emulator on port ${PORT}..."
        TIMEOUT=30
        for i in $(seq 1 ${TIMEOUT}); do
          if nc -z 127.0.0.1 ${PORT} 2>/dev/null; then
            echo "✅ Firestore emulator is ready on port ${PORT} (PID: ${EMULATOR_PID})"
            exit 0
          fi
          # Check if process is still running
          if ! kill -0 ${EMULATOR_PID} 2>/dev/null; then
            echo "❌ Emulator process died unexpectedly"
            cat firestore-emulator.log || true
            exit 1
          fi
          sleep 1
        done

        echo "❌ Timeout waiting for Firestore emulator"
        cat firestore-emulator.log || true
        exit 1
